apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: mattiyeshurun/fastapi-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql-service" 
        - name: DB_PASSWORD
          value: "root_password"